name: Remote Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull latest code
        run: |
          cd "C:\Users\kshit\Downloads\resumeapp"
          git pull origin main
      - name: Restart Service (Optional)
        run: |
          uv run python app.py
        working-directory: "C:/Users/kshit/Downloads/resumeapp"
