name: Remote Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull latest code
        run: |
          cd "C:\Users\kshit\Downloads\resumeapp"
          git pull origin main
      - name: Deploy
        run: cmd /c start /b C:\Users\kshit\Downloads\resumeapp\deploy.bat
