name: Remote Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull latest code
        run: |
          cd "C:\Users\kshit\Downloads\resumeapp"
          git pull origin main
      - name: Deploy with PM2
        run: |
          # Try to delete the old process, but don't crash if it doesn't exist
          pm2 delete resume-app 2>$null || $null

          # Start the new one
          pm2 start app.py --name "resume-app" --interpreter "uv" --interpreter-args "run python"
        working-directory: "C:/Users/kshit/Downloads/resumeapp"
